### ISSUE TITLE
Thesis

### ISSUE THREAD

**Issue by MarianAldenhoevel** [Thimbleby/Corvus#1]
Hi,

Is your thesis available online somewhere?

Regards, Marian

**Comment by Thimbleby** [comment]
Hi Marian,

You may be able to access it here:
https://solo.bodleian.ox.ac.uk/primo-explore/fulldisplay?docid=TN_cdi_gale_infotracacademiconefile_A513028904&context=PC&vid=SOLO&lang=en_US&search_scope=LSCOP_ALL&adaptor=primo_central_multiple_fe&tab=local&query=any,contains,Isaac%20Thimbleby&offset=0

Let me know if you can’t get access, and I’ll upload a copy.

Mind if I ask what your interest in the topic is?

Best regards,
Isaac

**Comment by Thimbleby** [comment]
Also - and this is just idle curiosity - where did you realise this was my PhD project from?

**Comment by Thimbleby** [comment]
Hi Marian,

I've uploaded a copy of my Thesis here.

Best regards,
Isaac
