### ISSUE TITLE
Thesis #1

### ISSUE THREAD

**Issue by OttaviaE** [Thimbleby/Corvus#2]
Hey Isaac!

Corvus is amazing, thank you for your work! 
My research group and I (University of Padua, Italy) are currently working on the development of adaptive testing procedures for cognitive tests, including Raven's matrices. We'd love to read your thesis and/or any publication related to Corvus. 
I see there's another issue titled "Thesis", I've already tried to follow the link you posted, but with no success (it appears I do not have access). So, please, would you mind uploading your Thesis? We'd really appreaciate it. 

Cheers! 

Ottavia

**Comment by Thimbleby** [comment]
Hi Ottavia!

you should be able to access my thesis at the link below. I no longer have any special access myself, so I think it is public? If it doesn’t work for you please let me know.

https://solo.bodleian.ox.ac.uk/primo-explore/fulldisplay?docid=TN_cdi_gale_infotracacademiconefile_A513028904&context=PC&vid=SOLO&lang=en_US&search_scope=LSCOP_ALL&adaptor=primo_central_multiple_fe&tab=local&query=any,contains,Isaac%20thimbleby&offset=0

**Comment by Thimbleby** [comment]
Hi Ottavia,

Thank you for your message!

I've uploaded a copy of my thesis here. Please do let me know about anything you end up using Corvus for - I'd be delighted to hear about it.

Best regards,
Isaac

**Comment by Thimbleby** [comment]
In case they are of interest, I also have short term memory and executive function tests uploaded to GitHub in their own repositories. But they were far, far smaller projects - they were also done while working on my thesis, but this was the main focus.

**Comment by OttaviaE** [comment]
Thank you so much for uploading your thesis!! We really appreciate it. 

I think we're using Corvus to generate Raven-like stimuli with our own generative rules. I'll keep you posted on any advance we're making! Most probably, you're gonna find the updates on my GH profile. 

Concerning the other tests: we'll take a look, they sound interesting and probably useful for the aim of our project. 

Thanks again!!
